import Header from "../../components/Header";
import SearchBar from "./components/SearchBar";
import TutorList from "./components/TutorList";
import Head from "next/head";

export default function SearchPage() {
	return (
		<div>
			<Head>
				<title>Web Tutor</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
					integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
					crossorigin="anonymous"
				/>
			</Head>
			<main>
				<div className="md:px-8 sm:px-1">
					<Header />
					<div className="container px-4 m-auto">
						<h1>This is Search Page</h1>
						<SearchBar />
						<TutorList />
					</div>
				</div>
			</main>
		</div>
	);
}
